# Generated by Django 3.2.18 on 2023-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('mobile_number', models.CharField(max_length=10, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ')),
                ('admitted_on', models.DateField(auto_now_add=True)),
                ('registration_date', models.DateField(default='dd/mm/yyyy', verbose_name='Ngày đăng kí')),
                ('registration_upto', models.DateField(verbose_name='Hạn đăng kí')),
                ('dob', models.DateField(default='dd/mm/yyyy', verbose_name='Ngày sinh')),
                ('subscription_type', models.CharField(choices=[('gym', 'Gym'), ('cross_fit', 'Cross Fit'), ('gym_and_cross_fit', 'Gym + Cross Fit'), ('pt', 'Personal Training')], default='gym', max_length=30, verbose_name='Khóa đăng kí')),
                ('subscription_period', models.CharField(choices=[('1', '1 tháng'), ('2', '2 tháng'), ('3', '3 tháng'), ('4', '4 tháng'), ('5', '5 tháng'), ('6', '6 tháng'), ('7', '7 tháng'), ('8', '8 tháng'), ('9', '9 tháng'), ('10', '10 tháng'), ('11', '11 tháng'), ('12', '12 tháng')], default='1', max_length=30, verbose_name='Thời gian đăng kí')),
                ('amount', models.CharField(max_length=30, verbose_name='Số tiền nộp')),
                ('fee_status', models.CharField(choices=[('paid', 'Đã thanh toán'), ('pending', 'Chưa thanh toán')], default='paid', max_length=30, verbose_name='Trạng thái nộp tiền')),
                ('notification', models.IntegerField(blank=True, default=2)),
                ('stop', models.IntegerField(blank=True, choices=[(0, 'Đang hoạt động'), (1, 'Đã ngừng tham gia')], default=0, verbose_name='Trạng thái hoạt động')),
            ],
        ),
    ]
