# Generated by Django 3.1.2 on 2023-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='medical_history',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Tiền sử bệnh'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Số điện thoại'),
        ),
    ]
